# Generated by Django 4.2.9 on 2024-05-13 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="excerpt",),
    ]
